import re as re_mod
from pathlib import Path

# Build the document_loader.py content using chr() for special chars
backtick = chr(96)
bs = chr(92)

lines = []
lines.append('import re')
lines.append('from pathlib import Path')
lines.append('from typing import List')
lines.append('')
lines.append('from langchain_core.documents import Document')
lines.append('')
lines.append('')
lines.append('def _clean_markdown(text):')
lines.append('    text = re.sub(r\"!' + bs + '[.*?' + bs + ']' + bs + '(.*?' + bs + ')\", \"\", text)')
lines.append('    text = re.sub(r\"' + backtick + '([^' + backtick + ']+)' + backtick + '\", r\"' + bs + '1\", text)')
lines.append('    text = re.sub(r\"' + bs + 'n{3,}\", \"' + bs + 'n' + bs + 'n\", text)')
lines.append('    return text.strip()')
lines.append('')
lines.append('')
lines.append('def load_documents(documents_dir):')
lines.append('    doc_path = Path(documents_dir)')
lines.append('    if not doc_path.exists():')
lines.append('        raise FileNotFoundError(f\"Document directory not found: {documents_dir}\")')
lines.append('')
lines.append('    documents = []')
lines.append('    md_files = sorted(doc_path.glob(\"*.md\"))')
lines.append('')
lines.append('    if not md_files:')
lines.append('        raise ValueError(f\"No .md files found in {documents_dir}\")')
lines.append('')
lines.append('    for file_path in md_files:')
lines.append('        text = file_path.read_text(encoding=\"utf-8\")')
lines.append('        cleaned_text = _clean_markdown(text)')
lines.append('')
lines.append('        doc = Document(')
lines.append('            page_content=cleaned_text,')
lines.append('            metadata={')
lines.append('                \"source\": file_path.name,')
lines.append('                \"file_path\": str(file_path),')
lines.append('            },')
lines.append('        )')
lines.append('        documents.append(doc)')
lines.append('')
lines.append('    print(f\"Loaded {len(documents)} documents\")')
lines.append('    for doc in documents:')
lines.append('        src = doc.metadata[\"source\"]')
lines.append('        clen = len(doc.page_content)')
lines.append('        print(f\"  - {src} ({clen} chars)\")')
lines.append('')
lines.append('    return documents')

out = Path(r'D:\luckin-rag-knowledge-base\rag_app\loader\document_loader.py')
out.write_text(chr(10).join(lines) + chr(10), encoding='utf-8')
print('document_loader.py rewritten successfully')
