import re as re_mod
from pathlib import Path

code = []
code.append('import re')
code.append('from pathlib import Path')
code.append('from typing import List')
code.append('')
code.append('from langchain_core.documents import Document')
code.append('')
code.append('')
code.append('def _clean_markdown(text):')
code.append('    text = re.sub(r\"!\\\\[.*?\\\\]\\\\(.*?\\\\)\", \"\", text)')
code.append('    text = re.sub(r\"([^]+)\", r\"\\\\1\", text)')
code.append('    text = re.sub(r\"\\\\n{3,}\", \"\\\\n\\\\n\", text)')
code.append('    return text.strip()')
code.append('')
code.append('')
code.append('def load_documents(documents_dir):')
code.append('    doc_path = Path(documents_dir)')
code.append('    if not doc_path.exists():')
code.append('        raise FileNotFoundError(f\"Document directory not found: {documents_dir}\")')
code.append('')
code.append('    documents = []')
code.append('    md_files = sorted(doc_path.glob(\"*.md\"))')
code.append('')
code.append('    if not md_files:')
code.append('        raise ValueError(f\"No .md files found in {documents_dir}\")')
code.append('')
code.append('    for file_path in md_files:')
code.append('        text = file_path.read_text(encoding=\"utf-8\")')
code.append('        cleaned_text = _clean_markdown(text)')
code.append('')
code.append('        doc = Document(')
code.append('            page_content=cleaned_text,')
code.append('            metadata={')
code.append('                \"source\": file_path.name,')
code.append('                \"file_path\": str(file_path),')
code.append('            },')
code.append('        )')
code.append('        documents.append(doc)')
code.append('')
code.append('    print(f\"Loaded {len(documents)} documents\")')
code.append('    for doc in documents:')
code.append('        src = doc.metadata[\"source\"]')
code.append('        clen = len(doc.page_content)')
code.append('        print(f\"  - {src} ({clen} chars)\")')
code.append('')
code.append('    return documents')

out = Path(r'D:\luckin-rag-knowledge-base\rag_app\loader\document_loader.py')
out.write_text(chr(10).join(code) + chr(10), encoding='utf-8')
print('Fixed document_loader.py')
