import sys
html = []
html.append('<!DOCTYPE html>')
html.append('<html lang="zh-CN">')
html.append('<head>')
html.append('<meta charset="UTF-8">')
html.append('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
html.append('<title>瑞幸咖啡知识库问答</title>')
html.append('<style>')
html.append('*{margin:0;padding:0;box-sizing:border-box}')
html.append('body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;background:#f5f5f5;color:#333;height:100vh;display:flex;flex-direction:column}')
html.append('.header{background:#003778;color:white;padding:16px 24px;text-align:center;flex-shrink:0}')
html.append('.header h1{font-size:20px;font-weight:600}')
html.append('.header p{font-size:13px;opacity:.8;margin-top:4px}')
html.append('.chat-container{flex:1;overflow-y:auto;padding:20px 24px;display:flex;flex-direction:column;gap:16px}')
html.append('.message{max-width:80%;padding:12px 16px;border-radius:12px;line-height:1.6;font-size:14px;word-wrap:break-word}')
html.append('.message.user{align-self:flex-end;background:#003778;color:white;border-bottom-right-radius:4px}')
html.append('.message.assistant{align-self:flex-start;background:white;border:1px solid #e0e0e0;border-bottom-left-radius:4px}')
html.append('.sources{margin-top:8px;padding-top:8px;border-top:1px solid #eee;font-size:12px;color:#888}')
html.append('.sources-title{font-weight:600;color:#666;margin-bottom:4px}')
html.append('.source-item{margin-top:4px;padding:6px 8px;background:#f9f9f9;border-radius:6px;border-left:3px solid #003778}')
html.append('.source-item .source-name{font-weight:600;color:#003778}')
html.append('.input-area{padding:16px 24px;background:white;border-top:1px solid #e0e0e0;flex-shrink:0}')
html.append('.input-wrapper{display:flex;gap:8px;max-width:800px;margin:0 auto}')
html.append('.input-wrapper input{flex:1;padding:12px 16px;border:1px solid #ddd;border-radius:8px;font-size:14px;outline:none}')
html.append('.input-wrapper input:focus{border-color:#003778}')
html.append('.input-wrapper button{padding:12px 24px;background:#003778;color:white;border:none;border-radius:8px;font-size:14px;cursor:pointer}')
html.append('.input-wrapper button:hover{background:#004ba0}')
html.append('.input-wrapper button:disabled{background:#aaa;cursor:not-allowed}')
html.append('.welcome{text-align:center;padding:40px 20px;color:#888}')
html.append('.welcome h2{font-size:18px;color:#555;margin-bottom:12px}')
html.append('.suggestions{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;margin-top:16px}')
html.append('.suggestion-btn{padding:8px 16px;background:white;border:1px solid #ddd;border-radius:20px;font-size:13px;cursor:pointer;color:#555}')
html.append('.suggestion-btn:hover{border-color:#003778;color:#003778}')
html.append('.loading{display:flex;align-items:center;gap:8px;color:#888;font-size:13px}')
html.append('.dot{animation:blink 1.4s infinite both}')
html.append('.dot:nth-child(2){animation-delay:.2s}')
html.append('.dot:nth-child(3){animation-delay:.4s}')
html.append('@keyframes blink{0%,80%,100%{opacity:0}40%{opacity:1}}')
html.append('</style>')
html.append('</head>')
html.append('<body>')
html.append('<div class="header">')
html.append('<h1>瑞幸咖啡知识库问答</h1>')
html.append('<p>基于 RAG 的企业知识智能检索系统</p>')
html.append('</div>')
html.append('<div class="chat-container" id="chatContainer">')
html.append('<div class="welcome" id="welcomeScreen">')
html.append('<h2>欢迎提问关于瑞幸咖啡的任何问题</h2>')
html.append('<p>点击以下示例问题开始，或直接输入你自己的问题</p>')
html.append('<div class="suggestions">')
html.append('<button class="suggestion-btn" onclick="askSuggestion(this)">瑞幸咖啡是什么时候成立的？</button>')
html.append('<button class="suggestion-btn" onclick="askSuggestion(this)">瑞幸咖啡的商业模式是什么？</button>')
html.append('<button class="suggestion-btn" onclick="askSuggestion(this)">生椰拿铁为什么这么受欢迎？</button>')
html.append('<button class="suggestion-btn" onclick="askSuggestion(this)">酱香拿铁的销量如何？</button>')
html.append('<button class="suggestion-btn" onclick="askSuggestion(this)">瑞幸咖啡的主要竞争对手有哪些？</button>')
html.append('<button class="suggestion-btn" onclick="askSuggestion(this)">瑞幸咖啡2024年的营收是多少？</button>')
html.append('</div>')
html.append('</div>')
html.append('</div>')
html.append('<div class="input-area">')
html.append('<div class="input-wrapper">')
html.append('<input type="text" id="questionInput" placeholder="输入你的问题..." onkeydown="if(event.key===\'Enter\')sendMessage()">')
html.append('<button id="sendBtn" onclick="sendMessage()">发送</button>')
html.append('</div>')
html.append('</div>')
html.append('<script>')
html.append('var API_BASE = "http://localhost:8000";')
html.append('var chatContainer = document.getElementById("chatContainer");')
html.append('var questionInput = document.getElementById("questionInput");')
html.append('var sendBtn = document.getElementById("sendBtn");')
html.append('var welcomeScreen = document.getElementById("welcomeScreen");')
html.append('')
html.append('function addMessage(role, content, sources) {')
html.append('  if (welcomeScreen) welcomeScreen.style.display = "none";')
html.append('  var div = document.createElement("div");')
html.append('  div.className = "message " + role;')
html.append('  var html = content.replace(/\\n/g, "<br>");')
html.append('  if (sources && sources.length > 0) {')
html.append('    html += \'<div class="sources"><div class="sources-title">参考来源：</div>\';')
html.append('    sources.forEach(function(s) {')
html.append('      html += \'<div class="source-item"><span class="source-name">\'+s.source+\'</span><br>\'+s.content+\'</div>\';')
html.append('    });')
html.append('    html += "</div>";')
html.append('  }')
html.append('  div.innerHTML = html;')
html.append('  chatContainer.appendChild(div);')
html.append('  chatContainer.scrollTop = chatContainer.scrollHeight;')
html.append('}')
html.append('')
html.append('function addLoading() {')
html.append('  var div = document.createElement("div");')
html.append('  div.className = "message assistant loading";')
html.append('  div.id = "loadingMsg";')
html.append('  div.innerHTML = "思考中 <span class=\\"dot\\">.</span><span class=\\"dot\\">.</span><span class=\\"dot\\">.</span>";')
html.append('  chatContainer.appendChild(div);')
html.append('  chatContainer.scrollTop = chatContainer.scrollHeight;')
html.append('}')
html.append('')
html.append('function removeLoading() {')
html.append('  var el = document.getElementById("loadingMsg");')
html.append('  if (el) el.remove();')
html.append('}')
html.append('')
html.append('async function sendMessage() {')
html.append('  var question = questionInput.value.trim();')
html.append('  if (!question) return;')
html.append('  questionInput.value = "";')
html.append('  addMessage("user", question);')
html.append('  sendBtn.disabled = true;')
html.append('  sendBtn.textContent = "发送中...";')
html.append('  addLoading();')
html.append('  try {')
html.append('    var resp = await fetch(API_BASE + "/ask", {')
html.append('      method: "POST",')
html.append('      headers: {"Content-Type": "application/json"},')
html.append('      body: JSON.stringify({question: question})')
html.append('    });')
html.append('    removeLoading();')
html.append('    if (!resp.ok) {')
html.append('      var err = await resp.json();')
html.append('      addMessage("assistant", "\\u274c " + (err.detail || "请求失败"));')
html.append('      return;')
html.append('    }')
html.append('    var data = await resp.json();')
html.append('    addMessage("assistant", data.answer, data.sources);')
html.append('  } catch(e) {')
html.append('    removeLoading();')
html.append('    addMessage("assistant", "\\u274c 无法连接到 API 服务，请确认服务已启动");')
html.append('  }')
html.append('  sendBtn.disabled = false;')
html.append('  sendBtn.textContent = "发送";')
html.append('}')
html.append('')
html.append('function askSuggestion(btn) {')
html.append('  questionInput.value = btn.textContent;')
html.append('  sendMessage();')
html.append('}')
html.append('</script>')
html.append('</body>')
html.append('</html>')

with open(r'D:\luckin-rag-knowledge-base\frontend\index.html', 'w', encoding='utf-8', newline='') as f:
    f.write('\n'.join(html))
print('Written', len('\n'.join(html)), 'bytes')
